# Don't print a new line at the start of the prompt
add_newline = false

# Make a prompt a single line instead of two
[line_break]
disabled = true

# Replace the ">" symbol with "->"
[character]
vicmd_symbol = "[<<<>>>](white)"
success_symbol = "[>>><<<](white)"	
error_symbol = "[<<<<<<](white)"

# Use custom format 
# format = """
# $all
# """
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """"""
# """

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = true

[time]
disabled = false

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[[battery.display]]  # "bold yellow" style when capacity is between 30% and 70%
threshold = 70
style = "bold blue"

[directory]
truncation_length = 2
truncate_to_repo = true
disabled = false
truncation_symbol = "…/"


